LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := Remove_Packages
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_OVERRIDES_PACKAGES := ANGLE AndroidAutoStubPrebuilt
LOCAL_OVERRIDES_PACKAGES += Aperture AmbientSensePrebuilt
LOCAL_OVERRIDES_PACKAGES += CalendarGooglePrebuilt
LOCAL_OVERRIDES_PACKAGES += Chrome
LOCAL_OVERRIDES_PACKAGES += FilesPrebuilt
LOCAL_OVERRIDES_PACKAGES += GCS
LOCAL_OVERRIDES_PACKAGES += GoogleTTS
LOCAL_OVERRIDES_PACKAGES += Photos
LOCAL_OVERRIDES_PACKAGES += SCONE
LOCAL_OVERRIDES_PACKAGES += TrichromeLibrary
LOCAL_OVERRIDES_PACKAGES += WebViewGoogle
LOCAL_OVERRIDES_PACKAGES += talkback
LOCAL_UNINSTALLABLE_MODULE := true
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_SRC_FILES := /dev/null
include $(BUILD_PREBUILT)
